check for missing deps, cleanups

diff --git a/quickrepo b/quickrepo
--- a/quickrepo
+++ b/quickrepo
@@ -1,24 +1,9 @@
 #!/bin/bash -e
 #
-# Build a debian repository for a set of packages from .changes files.
+# Build a debian repository for .deb or .changes files.
 #
 
 SCRIPT=$(basename "$0")
-
-# variables used by reprepro
-export REPREPRO_CONFIG_DIR
-export REPREPRO_BASE_DIR
-export GNUPGHOME
-
-# command-line option defaults
-OPT_ARCHES="source $(dpkg-architecture -q DEB_BUILD_ARCH)"
-OPT_ORIGIN="quickrepo"
-OPT_REPODIR="repo"
-OPT_CODENAME=$(lsb_release -cs)
-OPT_GPGKEY="default"
-OPT_VERBOSE=""
-declare -a OPT_FILES=()
-
 
 msg() {
     echo "$SCRIPT - $*"
@@ -33,21 +18,14 @@ error_exit() {
     exit 2
 }
 
-print_help() {
-    cat <<EOF
-Usage: $SCRIPT [options] <files...>
-
- -a ARCHES     space-separated list of repository arches (default: "$OPT_ARCHES")
- -c CODENAME   value for the repository "Codename" (default: "$OPT_CODENAME")
- -d REPODIR    create the repository under REPODIR (default: "$OPT_REPODIR")
- -g GPGKEY     fingerprint of GPG key to use to sign the repository
-               (default: default key from GPG config)
- -h            print this help
- -o ORIGIN     value for the repository "Origin" (default: "$OPT_ORIGIN")
- -v            verbose operations
-EOF
-}
-
+# command-line option defaults
+OPT_ARCHES="source $(dpkg-architecture -q DEB_BUILD_ARCH)"
+OPT_ORIGIN="quickrepo"
+OPT_REPODIR="repo"
+OPT_CODENAME=$(lsb_release -cs)
+OPT_GPGKEY="default"
+OPT_VERBOSE=""
+declare -a OPT_FILES=()
 
 parse_args() {
     local optstring="a:c:d:g:ho:v"
@@ -69,7 +47,6 @@ parse_args() {
                 ;;
             h)
                 print_help
-                exit 1
                 ;;
             o)
                 OPT_ORIGIN="$OPTARG"
@@ -87,6 +64,43 @@ parse_args() {
         shift "$((OPTIND-1))"
     fi
     OPT_FILES+=("$@")
+
+    if [ "${#OPT_FILES[@]}" -eq 0 ]; then
+        print_help
+    fi
+}
+
+print_help() {
+    cat <<EOF
+Usage: $SCRIPT [options] <files...>
+
+ -a ARCHES     space-separated list of repository arches (default: "$OPT_ARCHES")
+ -c CODENAME   value for the repository "Codename" (default: "$OPT_CODENAME")
+ -d REPODIR    create the repository under REPODIR (default: "$OPT_REPODIR")
+ -g GPGKEY     fingerprint of GPG key to use to sign the repository
+               (default: default key from GPG config)
+ -h            print this help
+ -o ORIGIN     value for the repository "Origin" (default: "$OPT_ORIGIN")
+ -v            verbose operations
+EOF
+    exit 1
+}
+
+is_deb_installed() {
+    dpkg-query -W -f'${Status}\n' "$1" 2>/dev/null | grep -q ^install
+}
+
+check_deps() {
+    local deps="dpkg-dev lsb-release reprepro"
+    local -a missing=()
+    for dep in $deps; do
+        is_deb_installed "$dep" || missing+=("$dep")
+    done
+
+    if [ "${#missing[@]}" -gt 0 ]; then
+        echo "Missing packages, please install them with:  sudo apt install ${missing[*]}"
+        exit 1
+    fi
 }
 
 check_files() {
@@ -131,7 +145,7 @@ setup_reprepro() {
 Codename: $codename
 Architectures: $arches
 Origin: $origin
-Label: Test repository ($origin)
+Label: Repository for $origin
 Components: main
 SignWith: $signkey
 EOF
@@ -161,4 +175,5 @@ import_packages() {
 
 parse_args "$@"
 check_files "${OPT_FILES[@]}"
+check_deps
 build_repo "$OPT_REPODIR" "$OPT_ARCHES" "$OPT_ORIGIN" "$OPT_CODENAME" "$OPT_GPGKEY" "${OPT_FILES[@]}"
